apiVersion: kustomize.config.k8s.io/v1beta1

namespace: liknot-controller

configMapGenerator:
  - name: envoy-config
    files:
      - file/envoy-bootstrap.yaml
resources:
  - envoy-deployment.yaml
