apiVersion: v1
kind: Namespace
metadata:
  name: liknot-controller

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: liknot-controller
  namespace: liknot-controller

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: liknot-controller
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - services
      - pods
      - endpoints
    verbs:
      - get
      - list
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: liknot-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: liknot-controller
subjects:
  - kind: ServiceAccount
    name: liknot-controller
    namespace: liknot-controller

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liknot-controller
  namespace: liknot-controller
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liknot-controller
  template:
    metadata:
      labels:
        app: liknot-controller
    spec:
      serviceAccountName: liknot-controller
      containers:
        - name: liknot-controller
          image: controller:latest
          ports:
            - containerPort: 80
