apiVersion: v1
kind: Namespace
metadata:
  name: liknot-controller

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: liknot-controller
  namespace: liknot-controller

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: liknot-controller
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - services
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - ingresses/status
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: liknot-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: liknot-controller
subjects:
  - kind: ServiceAccount
    name: liknot-controller
    namespace: liknot-controller

---
apiVersion: v1
kind: Service
metadata:
  name: liknot-controller
  namespace: liknot-controller
spec:
  type: ClusterIP
  selector:
    app: liknot-controller
  ports:
    - port: 10081
      targetPort: 10081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liknot-controller
  namespace: liknot-controller
  labels:
    app: liknot-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liknot-controller
  template:
    metadata:
      labels:
        app: liknot-controller
    spec:
      serviceAccountName: liknot-controller
      containers:
        - name: liknot-controller
          image: controller:latest
          ports:
            - containerPort: 80
